### ISSUE TITLE
FR: Include forecasts for Energy/Cost flexup 

### ISSUE THREAD

**Issue by purcell-lab** [gurrier/localvolts#4]
Nice work on this integration. 

Do you have plans to add a sensor for the forecast prices for the next 24 hours which is available from the LV API?

**Comment by gurrier** [comment]
Yes, it is on the TODO list next.

**Comment by gurrier** [comment]
@purcell-lab Can I confirm what version you are running?

**Comment by purcell-lab** [comment]
> what version you are running?

0.4.1

![image](https://github.com/user-attachments/assets/18860717-36a7-4a87-95f5-158878dbcae0)

**Comment by sgresham** [comment]
I have a fork of this with a working forecast. Just making sure it works correctly but will send a PR when I am happy with it. Welcome to look at mine in the meantime

**Comment by gurrier** [comment]
> I have a fork of this with a working forecast. Just making sure it works correctly but will send a PR when I am happy with it. Welcome to look at mine in the meantime

There appears to be some dependency on having EMHASS Integration introduced in your code.  Is this necessary for your desired outcome?  @sgresham

**Comment by sgresham** [comment]
Howdy. No I should have split it apart. The forecast bit is complete, but I wanted to have an option for emhass to make it easier where people would want it. At the moment not enabling the emhass option allows the forecast to work as expected. I wanted to talk to you about extending the capabilities to have the emhass option, but will submit a PR with just the forecast for the moment

**Comment by sgresham** [comment]
I have removed the EMHASS from my main branch @gurrier , did you want to review before I send for a PR?

**Comment by sgresham** [comment]
ok. PR created
https://github.com/gurrier/localvolts/pull/20

**Comment by gurrier** [comment]
Thanks @sgresham will test it.

**Comment by sgresham** [comment]
Any thoughts @gurrier ?

**Comment by gurrier** [comment]
> Any thoughts [@gurrier](https://github.com/gurrier) ?

Sorry, @sgresham  I've been a bit distracted with chasing up bugs elsewhere but expect I will get to this within the next few days.
Thanks for submitting.

**Comment by purcell-lab** [comment]
The forecasts seem to be available now in _sensor.forcasted_costs_flex_up_

<img width="592" height="146" alt="Image" src="https://github.com/user-attachments/assets/fdaf6778-252b-4b4e-afdc-89a6b982d3c5" />

```yaml
state:
  translated: 35.886 c/kWh
  raw: "35.886"
  last_changed: "2026-04-14T10:35:08.978Z"
  last_updated: "2026-04-14T10:35:18.802Z"
attributes:
  forecast:
    - duration: 5
      start_time: "2026-04-14T10:40:00+00:00"
      end_time: "2026-04-14T10:45:00+00:00"
      earningsFlexUp: 10.03068
      costsFlexUp: 33.1634
    - duration: 5
      start_time: "2026-04-14T10:45:00+00:00"
      end_time: "2026-04-14T10:50:00+00:00"
      earningsFlexUp: 10.03068
      costsFlexUp: 33.1634
    - duration: 5
      start_time: "2026-04-14T10:50:00+00:00"
      end_time: "2026-04-14T10:55:00+00:00"
      earningsFlexUp: 10.03068
      costsFlexUp: 33.1634
```
