### ISSUE TITLE
Feature Request: Demand Window Sensor

### ISSUE THREAD

**Issue by obsoolete** [gurrier/localvolts#7]
Great work with the repo!

If possible, could you please add binary demand window sensor? This would help a lot with import automations.

**Comment by gurrier** [comment]
You should see an attribute for 'demandInterval' for the costsFlexUp sensor in v0.5.1

**Comment by gurrier** [comment]
If you want to create a sensor for it that you can display in a dashboard in Home Assistant then try adding this to your configuration.yaml file.   

```
  - platform: template
    sensors:
      demand_interval:
        friendly_name: "In Demand Interval"
        value_template: "{{ 'On' if state_attr('sensor.costsflexup', 'demandInterval') | int == 1 else 'Off' }}"
        icon_template: "mdi:clock"
```

The sensor is then referenced as entity: sensor.demand_interval

**Comment by obsoolete** [comment]
Thank you gurrier!

If you use the new template format 

```
template:
  - binary_sensor:
      - name: "Demand Window"
        unique_id: sensor.demand_window
        state: >
          "{{ 'On' if state_attr('sensor.costsflexup', 'demandInterval') | int == 1 else 'Off' }}"
```

Out of curiosity, any reason why you wouldn't add a 4th sensor as a binary sensor?

**Comment by gurrier** [comment]
Your template sensor is better as it uses the newer format.  Thanks.

I chose to implement as an Attribute since there are LOTS of fields returned by the API in each 5min interval and it gives a simpler path to add them in future if required.

**Comment by gurrier** [comment]
A small improvement might be this so that it becomes a true binary sensor rather than being returned as a string.

```
template:
  - binary_sensor:
      - name: "In Demand Interval"
        unique_id: "demand_interval"
        state: >
          {{ state_attr('sensor.costsflexup', 'demandInterval') | int == 1 }}
        icon: mdi:clock
```
